first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views


app_name = 'first_app'

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.user_login, name='login'),

]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from first_app import views
from django.conf.urls import include


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    url(r'^formpage/', views.form_name_view, name="form_name"),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special'),

]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class WebPage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(WebPage, on_delete=models.DO_NOTHING,)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo


def check_for_z(value):
    if value[0].lower() !='z':
        raise forms.ValidationError("Name Need to Start with Z")

class FormName(forms.Form):
    name = forms.CharField() # validators=[check_for_z]
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter you Email Again')
    text = forms.CharField(widget = forms.Textarea)
    botcatcher  = forms.CharField(required=False,
                                  widget=forms.HiddenInput,
                                  validators=[validators.MaxLengthValidator(0)])

    #  cleam particular field make a function named clean_<fieldname>
    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("GOTCHA BOT!!")
    #     return botcatcher
    # clean entire form

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email != vmail:
            raise forms.ValidationError("Make Sure Email Match")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from first_app.models import Topic, WebPage, AccessRecord
from django.http import HttpResponse
from . import forms
from first_app.forms import UserForm, UserProfileInfoForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse

# Create your views here.

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    my_type = type(webpages_list)
    date_dict = {'access_records': webpages_list, 'my_name': "jay", "my_type": my_type}
    return render(request, 'first_app/index.html', context = date_dict)

def form_name_view(request):
    form = forms.FormName()

    if request.method == "POST":
        form = forms.FormName(request.POST)
        if form.is_valid():
            # do something code
            print(form.cleaned_data['name'])
            print(form.cleaned_data['email'])
            print(form.cleaned_data['text'])



    return render(request, 'first_app/form_page.html', {'form' : form})

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form  = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user # OneToOneField

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_app/registration.html',
                                {'registered':registered,
                                'user_form':user_form,
                                'profile_form':profile_form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVATE")
        else:
            print("Someone tried to login and failed")
            print(f"username: {username} and password {password}")
            logged_in = "Invalid Login Details"
            return render(request, 'first_app/login.html', {'logged_in' : logged_in})
            #return HttpResponse("Invalid Login Details")

    else:
        return render(request, 'first_app/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You Are Logged In, Nice")

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>


    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <ul class="nav navbar-nav">

            <li> <a class="navbar-barnd" href="{% url 'index' %}"> DJANGO </a></li>
            <li> <a class="navbar-barnd" href="{% url 'admin:index' %}">ADMIN </a> </li>
            <li> <a class="navbar-barnd" href="{% url 'first_app:register' %}">Registration</a></li>

            {% if user.is_authenticated %}
            <li> <a class="navbar-barnd" href="{% url 'logout'%}">Logout</a></li>
            {%else%}
            <li> <a class="navbar-barnd" href="{% url 'first_app:login' %}">Login</a></li>
            {%endif%}
          </ul>
        </div>
    </nav>


    <div class="container">
      {% block body_block%}
      {% endblock %}
    </div>

  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Form</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>


    <h1> Fil Out the Form</h1>
    <div class="container">
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>

    </div>

  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block%}

  <div class="jumbotron">
    <h1>Django Level Five</h1>
      
  </div>

{% endblock %}

first_project/templates/first_app/login.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="jumbotron">

    <h1>Please Login</h1>
      <form action="{% url 'first_app:login' %}" method="post">
      {% csrf_token %}

      <hr class="my-4">

      <label for="username">Username</label>
      <input type="text" name="username" placeholder="Enter UserName">

      <br>

      <label for="password">Password</label>
      <input type="password" name="password" placeholder="Enter Password">

      <br><br>

      <input type="submit" name=""class="btn btn-primary" value="Submit">
      <h3> {{logged_in }}</h3>
    </form>
</div>

{% endblock %}

first_project/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load static %}


{% block body_block %}


  <div class="jumbotron">

      {% if registered %}
        <h1>Thank You For Registration</h1>
        {%else%}

        <h1>Register Here</h1>
        <hr class="4">

        <h3>Fill Out Form</h3>
        <hr class="my-4">


        <form  method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <hr class="my-4">
          <input type="submit" class="btn btn-primary" name="" value="Register">
        </form>
      {%endif%}
  </div>
{% endblock %}